# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 18 Oct 2021 06:34:47 +0000
*               @ALL          1
*               @user         8
