<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jurjen
 * Date: Mon, 18 Oct 2021 13:53:11 +0000
 */

$conf['title'] = 'Jurjens\' notes';
$conf['template'] = 'starterbootstrap';
$conf['license'] = 'publicdomain';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
