<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jurjen
 * Date: Wed, 20 Oct 2021 19:11:19 +0000
 */

$conf['title'] = 'wiki.jurjen.dev';
$conf['license'] = 'publicdomain';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '2';
$conf['proxy']['user'] = 'jurjen';
$conf['proxy']['pass'] = '<b>ZVBzMmk2endYRWFKM2FB';
$conf['tpl']['starterbootstrap']['full_width'] = '1';
