<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jurjen
 * Date: Mon, 18 Oct 2021 13:58:17 +0000
 */

$conf['title'] = 'Personal notes';
$conf['template'] = 'starterbootstrap';
$conf['license'] = 'publicdomain';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['starterbootstrap']['hideTools'] = 1;
