# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 18 Oct 2021 06:34:47 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

jurjen:$1$bxMMEuUW$TDhY3ZU.2jhoGY77Se7FG.:jurjen:info@jurjen.dev:admin,user
